### ISSUE TITLE
Migration order on install

### ISSUE THREAD

**Issue by londoh** [harrygr/Creuset#10]
a small install issue is that migrations wont run.
Because of the ordering of the migration files the users table is created before roles and the FK on users -> roles cant be created

    [Illuminate\Database\QueryException]                                                                                                                                                                                              
    SQLSTATE[HY000]: General error: 1005 Can't create table 'creuset.#sql-a63_fada5' (errno: 150) (SQL: alter table `users` add constraint users_role_id_foreign foreign key (`role_id`) references `roles` (`id`) on delete cascade)

**Comment by harrygr** [comment]
Right you are. I'm developing with sqlite which doesn't seem to care about this so this bug went unnoticed. Fixed in a43dffad482cd90f19521e0e3c7188e5dcbfbd83
